Repository mandarine3ds/mandarine, pull requests merged in 2024-05, with the labels that each got.

#42 Implement Force Maximum GPU Clocks option
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/BooleanSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsAdapter.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/SwitchSettingViewHolder.kt
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#50 Fix Pokemon X crashing on some Mali devices
  src/video_core/shader/generator/spv_shader_gen.cpp
Labels: ready, fix

#52 Rework settings UI
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/RunnableSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/SubmenuSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/RunnableViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/SubmenuViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/ViewUtils.kt
  src/android/app/src/main/res/drawable/ic_audio.xml
  src/android/app/src/main/res/drawable/ic_camera_settings.xml
  src/android/app/src/main/res/drawable/ic_controls_settings.xml
  src/android/app/src/main/res/drawable/ic_general_settings.xml
  src/android/app/src/main/res/drawable/ic_graphics.xml
  src/android/app/src/main/res/drawable/ic_restore.xml
  src/android/app/src/main/res/drawable/ic_system_settings.xml
  src/android/app/src/main/res/layout/activity_settings.xml
  src/android/app/src/main/res/layout/list_item_setting.xml
  src/android/app/src/main/res/layout/list_item_setting_switch.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, ready
