Repository mandarine3ds/mandarine, pull requests merged in 2025-02, with the labels that each got.

#147 android: Implement GpuDriver import option
  src/android/app/build.gradle.kts
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/fragments/DriverManagerFragment.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/fragments/HomeSettingsFragment.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/utils/DriversFetcher.kt
  src/android/app/src/main/res/layout/dialog_progress.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#148 Fix cherrypicking mistake
  src/android/app/release/baselineProfiles/0/app-release.dm
  src/android/app/release/baselineProfiles/1/app-release.dm
  src/android/app/release/output-metadata.json
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/dialogs/ChatDialog.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/dialogs/NetPlayDialog.kt
Labels: fix

#150 android: Add uninstall game and open folder options to about game dialog
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/adapters/GameAdapter.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/utils/DocumentsTree.kt
  src/android/app/src/main/res/drawable/ic_open.xml
  src/android/app/src/main/res/drawable/ic_uninstall.xml
  src/android/app/src/main/res/layout/dialog_about_game.xml
  src/android/app/src/main/res/menu/game_context_menu_open.xml
  src/android/app/src/main/res/menu/game_context_menu_uninstall.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#152 android: Change the look of home card items
  src/android/app/src/main/res/layout/card_home_option.xml
Labels: refactor

#155 android: Refactor SetupFragment to support multipel page buttons
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/adapters/SetupAdapter.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/fragments/CopyDirProgressDialogFragment.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/fragments/SetupFragment.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/fragments/SetupWarningDialogFragment.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/model/SetupPage.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/ui/main/MainActivity.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/utils/MandarineDirectoryHelper.kt
  src/android/app/src/main/res/drawable/ic_permission.xml
  src/android/app/src/main/res/layout-land/page_setup.xml
  src/android/app/src/main/res/layout/page_button.xml
  src/android/app/src/main/res/layout/page_setup.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#159 android: Implement playtime tracking
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/activities/EmulationActivity.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/adapters/GameAdapter.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/utils/PlayTimeTracler.kt
  src/android/app/src/main/res/drawable/ic_divider.xml
  src/android/app/src/main/res/layout/dialog_about_game.xml
  src/android/app/src/main/res/menu/game_context_menu_uninstall.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#161 mandarine_qt: Allow to set server address on room_create
  src/mandarine_qt/multiplayer/host_room.cpp
  src/mandarine_qt/multiplayer/host_room.h
  src/mandarine_qt/multiplayer/host_room.ui
Labels: enhancement

#164 Rename PlayTimeTracler.kt to PlayTimeTracker.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/utils/PlayTimeTracker.kt
Labels: fix

#167 MNake logging more verbose
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/features/settings/model/BooleanSetting.kt
  src/android/app/src/main/jni/default_ini.h
  src/common/settings.h
Labels: refactor

#166 android: Fix controllers opening nav drawer even after being bound to a hotkey
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/activities/EmulationActivity.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/features/hotkeys/HotkeyUtility.kt
Labels: bug

#165 android: Add favorites feature to game list
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/adapters/GameAdapter.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/fragments/GamesFragment.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/model/Game.kt
  src/android/app/src/main/java/io/github/mandarine3ds/mandarine/model/GameListItem.kt
  src/android/app/src/main/res/drawable/ic_star.xml
  src/android/app/src/main/res/drawable/ic_star_frame.xml
  src/android/app/src/main/res/layout/card_game.xml
  src/android/app/src/main/res/layout/card_game_big.xml
  src/android/app/src/main/res/layout/dialog_about_game.xml
  src/android/app/src/main/res/layout/list_item_separator.xml
  src/android/app/src/main/res/menu/menu_game_filters.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement
